export const initialTableData = [
  {
    id: 1,
    propertyName: "Grand Plaza Hotel",
    location: "New York, NY",
    propertyId: "GP001",
    totalRooms: 150,
    activeCheckins: 45,
  },
  {
    id: 2,
    propertyName: "Sunset Resort",
    location: "Miami, FL",
    propertyId: "SR002",
    totalRooms: 200,
    activeCheckins: 89,
  },
  {
    id: 3,
    propertyName: "Mountain View Inn",
    location: "Denver, CO",
    propertyId: "MV003",
    totalRooms: 80,
    activeCheckins: 32,
  },
  {
    id: 4,
    propertyName: "Ocean Breeze Suites",
    location: "San Diego, CA",
    propertyId: "OB004",
    totalRooms: 120,
    activeCheckins: 67,
  },
  {
    id: 5,
    propertyName: "City Center Hotel",
    location: "Chicago, IL",
    propertyId: "CC005",
    totalRooms: 180,
    activeCheckins: 54,
  },
  {
    id: 6,
    propertyName: "Heritage Palace",
    location: "Boston, MA",
    propertyId: "HP006",
    totalRooms: 95,
    activeCheckins: 28,
  },
  {
    id: 7,
    propertyName: "Lakeside Retreat",
    location: "Seattle, WA",
    propertyId: "LR007",
    totalRooms: 60,
    activeCheckins: 18,
  },
  {
    id: 8,
    propertyName: "Desert Oasis",
    location: "Phoenix, AZ",
    propertyId: "DO008",
    totalRooms: 110,
    activeCheckins: 42,
  },
];

export const tableData = [
  {
    period: "Last 7 Days",
    totalCredits: 67,
    averagePerDay: "9.6/day",
    remainingCredits: 16,
    efficiency: "Excellent",
  },
  {
    period: "Last 30 Days",
    totalCredits: 246,
    averagePerDay: "8.2/day",
    remainingCredits: 18,
    efficiency: "Good",
  },
  {
    period: "Last 90 Days",
    totalCredits: 753,
    averagePerDay: "8.4/day",
    remainingCredits: 22,
    efficiency: "Good",
  },
  {
    period: "This Billing Cycle",
    totalCredits: 492,
    averagePerDay: "7.8/day",
    remainingCredits: 19,
    efficiency: "Excellent",
  },
];

export const consumptionData = [
  {
    id: 1,
    propertyName: "Grand Plaza Hotel",
    propertyId: "GP001",
    creditsAllocated: 300,
    creditsUsed: 285,
    remainingCredits: 15,
    averageDailyUsage: 3.2,
    lastTopupDate: "2024-11-15",
    creditStatus: "critical",
    utilization: 95,
  },
  {
    id: 2,
    propertyName: "Sunset Resort",
    propertyId: "SR002",
    creditsAllocated: 250,
    creditsUsed: 180,
    remainingCredits: 70,
    averageDailyUsage: 2.1,
    lastTopupDate: "2024-11-20",
    creditStatus: "low",
    utilization: 72,
  },
  {
    id: 3,
    propertyName: "Mountain View Inn",
    propertyId: "MV003",
    creditsAllocated: 150,
    creditsUsed: 89,
    remainingCredits: 61,
    averageDailyUsage: 1.5,
    lastTopupDate: "2024-11-10",
    creditStatus: "normal",
    utilization: 59,
  },
];

export const billingData = [
  {
    id: 1,
    invoiceNo: "INV-2024-001",
    invoiceDate: "2024-11-15",
    creditsPurchased: 500,
    paymentMode: "Credit Card",
    amountPaid: 25000,
    status: "paid",
    downloadUrl: "#",
  },
  {
    id: 2,
    invoiceNo: "INV-2024-002",
    invoiceDate: "2024-10-28",
    creditsPurchased: 300,
    paymentMode: "UPI",
    amountPaid: 15000,
    status: "paid",
    downloadUrl: "#",
  },
];