// Dashboard - Property Data
export const initialTableData = [
  {
    id: 1,
    propertyName: "Grand Plaza Hotel",
    location: "New York, NY",
    propertyId: "GP001",
    totalRooms: 150,
    activeCheckins: 45,
  },
  {
    id: 2,
    propertyName: "Sunset Resort",
    location: "Miami, FL",
    propertyId: "SR002",
    totalRooms: 200,
    activeCheckins: 89,
  },
  {
    id: 3,
    propertyName: "Mountain View Inn",
    location: "Denver, CO",
    propertyId: "MV003",
    totalRooms: 80,
    activeCheckins: 32,
  },
  {
    id: 4,
    propertyName: "Ocean Breeze Suites",
    location: "San Diego, CA",
    propertyId: "OB004",
    totalRooms: 120,
    activeCheckins: 67,
  },
  {
    id: 5,
    propertyName: "City Center Hotel",
    location: "Chicago, IL",
    propertyId: "CC005",
    totalRooms: 180,
    activeCheckins: 54,
  },
  {
    id: 6,
    propertyName: "Heritage Palace",
    location: "Boston, MA",
    propertyId: "HP006",
    totalRooms: 95,
    activeCheckins: 28,
  },
  {
    id: 7,
    propertyName: "Lakeside Retreat",
    location: "Seattle, WA",
    propertyId: "LR007",
    totalRooms: 60,
    activeCheckins: 18,
  },
  {
    id: 8,
    propertyName: "Desert Oasis",
    location: "Phoenix, AZ",
    propertyId: "DO008",
    totalRooms: 110,
    activeCheckins: 42,
  },
];

// Credit Overview - Period Data
export const tableData = [
  {
    period: "Last 7 Days",
    totalCredits: 67,
    averagePerDay: "9.6/day",
    remainingCredits: 16,
    efficiency: "Excellent",
  },
  {
    period: "Last 30 Days",
    totalCredits: 246,
    averagePerDay: "8.2/day",
    remainingCredits: 18,
    efficiency: "Good",
  },
  {
    period: "Last 90 Days",
    totalCredits: 753,
    averagePerDay: "8.4/day",
    remainingCredits: 22,
    efficiency: "Good",
  },
  {
    period: "This Billing Cycle",
    totalCredits: 492,
    averagePerDay: "7.8/day",
    remainingCredits: 19,
    efficiency: "Excellent",
  },
  {
    period: "Previous Billing Cycle",
    totalCredits: 508,
    averagePerDay: "8.1/day",
    remainingCredits: 12,
    efficiency: "Good",
  },
  {
    period: "Last 6 Months",
    totalCredits: 2890,
    averagePerDay: "8.0/day",
    remainingCredits: 110,
    efficiency: "Excellent",
  },
];

// Credit Consumption - Property Wise
export const consumptionData = [
  {
    id: 1,
    propertyName: "Grand Plaza Hotel",
    propertyId: "GP001",
    creditsAllocated: 300,
    creditsUsed: 285,
    remainingCredits: 15,
    averageDailyUsage: 3.2,
    lastTopupDate: "2024-11-15",
    creditStatus: "critical",
    utilization: 95,
  },
  {
    id: 2,
    propertyName: "Sunset Resort",
    propertyId: "SR002",
    creditsAllocated: 250,
    creditsUsed: 180,
    remainingCredits: 70,
    averageDailyUsage: 2.1,
    lastTopupDate: "2024-11-20",
    creditStatus: "normal",
    utilization: 72,
  },
  {
    id: 3,
    propertyName: "Mountain View Inn",
    propertyId: "MV003",
    creditsAllocated: 150,
    creditsUsed: 89,
    remainingCredits: 61,
    averageDailyUsage: 1.5,
    lastTopupDate: "2024-11-10",
    creditStatus: "normal",
    utilization: 59,
  },
  {
    id: 4,
    propertyName: "Ocean Breeze Suites",
    propertyId: "OB004",
    creditsAllocated: 200,
    creditsUsed: 145,
    remainingCredits: 55,
    averageDailyUsage: 2.8,
    lastTopupDate: "2024-11-18",
    creditStatus: "normal",
    utilization: 72.5,
  },
  {
    id: 5,
    propertyName: "City Center Hotel",
    propertyId: "CC005",
    creditsAllocated: 100,
    creditsUsed: 70,
    remainingCredits: 30,
    averageDailyUsage: 1.8,
    lastTopupDate: "2024-11-22",
    creditStatus: "low",
    utilization: 70,
  },
  {
    id: 6,
    propertyName: "Heritage Palace",
    propertyId: "HP006",
    creditsAllocated: 180,
    creditsUsed: 165,
    remainingCredits: 15,
    averageDailyUsage: 2.5,
    lastTopupDate: "2024-11-12",
    creditStatus: "critical",
    utilization: 91.7,
  },
  {
    id: 7,
    propertyName: "Lakeside Retreat",
    propertyId: "LR007",
    creditsAllocated: 120,
    creditsUsed: 95,
    remainingCredits: 25,
    averageDailyUsage: 1.9,
    lastTopupDate: "2024-11-19",
    creditStatus: "low",
    utilization: 79.2,
  },
  {
    id: 8,
    propertyName: "Desert Oasis",
    propertyId: "DO008",
    creditsAllocated: 220,
    creditsUsed: 150,
    remainingCredits: 70,
    averageDailyUsage: 2.4,
    lastTopupDate: "2024-11-21",
    creditStatus: "normal",
    utilization: 68.2,
  },
];

// Billing History - Invoice Data
export const billingData = [
  {
    id: 1,
    invoiceNo: "INV-2024-001",
    invoiceDate: "2024-11-15",
    creditsPurchased: 500,
    paymentMode: "Credit Card",
    amountPaid: 25000,
    status: "paid",
    downloadUrl: "#",
  },
  {
    id: 2,
    invoiceNo: "INV-2024-002",
    invoiceDate: "2024-10-28",
    creditsPurchased: 300,
    paymentMode: "UPI",
    amountPaid: 15000,
    status: "paid",
    downloadUrl: "#",
  },
  {
    id: 3,
    invoiceNo: "INV-2024-003",
    invoiceDate: "2024-10-15",
    creditsPurchased: 200,
    paymentMode: "Credit Card",
    amountPaid: 10000,
    status: "paid",
    downloadUrl: "#",
  },
  {
    id: 4,
    invoiceNo: "INV-2024-004",
    invoiceDate: "2024-09-30",
    creditsPurchased: 400,
    paymentMode: "Bank Transfer",
    amountPaid: 20000,
    status: "paid",
    downloadUrl: "#",
  },
  {
    id: 5,
    invoiceNo: "INV-2024-005",
    invoiceDate: "2024-09-15",
    creditsPurchased: 150,
    paymentMode: "Credit Card",
    amountPaid: 7500,
    status: "failed",
    downloadUrl: "#",
  },
  {
    id: 6,
    invoiceNo: "INV-2024-006",
    invoiceDate: "2024-08-28",
    creditsPurchased: 250,
    paymentMode: "UPI",
    amountPaid: 12500,
    status: "paid",
    downloadUrl: "#",
  },
  {
    id: 7,
    invoiceNo: "INV-2024-007",
    invoiceDate: "2024-08-15",
    creditsPurchased: 350,
    paymentMode: "Credit Card",
    amountPaid: 17500,
    status: "pending",
    downloadUrl: "#",
  },
  {
    id: 8,
    invoiceNo: "INV-2024-008",
    invoiceDate: "2024-07-30",
    creditsPurchased: 100,
    paymentMode: "Bank Transfer",
    amountPaid: 5000,
    status: "paid",
    downloadUrl: "#",
  },
  {
    id: 9,
    invoiceNo: "INV-2024-009",
    invoiceDate: "2024-07-15",
    creditsPurchased: 450,
    paymentMode: "Credit Card",
    amountPaid: 22500,
    status: "paid",
    downloadUrl: "#",
  },
  {
    id: 10,
    invoiceNo: "INV-2024-010",
    invoiceDate: "2024-06-30",
    creditsPurchased: 275,
    paymentMode: "UPI",
    amountPaid: 13750,
    status: "paid",
    downloadUrl: "#",
  },
];

// MIS Reports - Guest Records Data
export const guestRecords = [
  {
    id: 1,
    reservation: "RES4001",
    name: "Arjun Mehta",
    hotel: "Silver Sands",
    location: "Banjara Hills, Hyderabad",
    phone: "9876501234",
    verification: "Passport",
    faceMatch: "Match",
    checkIn: "2025-08-18 11:10 AM",
    staffName: "Priya Nair",
    gender: "Male",
    dob: "15 Jul 1985",
    nationality: "Indian",
    govtIdType: "Passport",
    govtIdNumber: "N1234567",
    email: "arjun.mehta@gmail.com",
    aadhaarVerification: {
      status: "Not Applicable",
      faceId: "Match",
      manualVerification: "Not Required",
      verifiedOn: "18 Aug 2025, 11:25 AM",
      verifiedBy: "HC-User201",
    },
    dependents: [],
  },
  {
    id: 2,
    reservation: "RES4002",
    name: "Meera Sharma",
    hotel: "Silver Sands",
    location: "Banjara Hills, Hyderabad",
    phone: "9987123456",
    verification: "Aadhaar",
    faceMatch: "Match",
    checkIn: "2025-08-18 02:00 PM",
    staffName: "Rahul Iyer",
    gender: "Female",
    dob: "22 Mar 1992",
    nationality: "Indian",
    govtIdType: "Aadhaar",
    govtIdNumber: "XXXX-XXXX-5612",
    email: "meera.sharma@gmail.com",
    aadhaarVerification: {
      status: "Verified",
      faceId: "Match",
      manualVerification: "Not Required",
      verifiedOn: "18 Aug 2025, 02:15 PM",
      verifiedBy: "HC-User205",
    },
    dependents: [{ name: "Riya Sharma", age: 3, guardian: "Meera Sharma" }],
  },
  {
    id: 3,
    reservation: "RES4003",
    name: "David Johnson",
    hotel: "Silver Sands",
    location: "Banjara Hills, Hyderabad",
    phone: "7890123456",
    verification: "Passport",
    faceMatch: "Match",
    checkIn: "2025-08-18 05:20 PM",
    staffName: "Sneha Reddy",
    gender: "Male",
    dob: "10 Jan 1980",
    nationality: "British",
    govtIdType: "Passport",
    govtIdNumber: "B9081234",
    email: "david.johnson@yahoo.com",
    aadhaarVerification: {
      status: "Not Applicable",
      faceId: "Match",
      manualVerification: "Not Required",
      verifiedOn: "18 Aug 2025, 05:35 PM",
      verifiedBy: "HC-User210",
    },
    dependents: [],
  },
  {
    id: 4,
    reservation: "RES4004",
    name: "Anjali Verma",
    hotel: "Silver Sands",
    location: "Banjara Hills, Hyderabad",
    phone: "9123456780",
    verification: "Aadhaar",
    faceMatch: "Match",
    checkIn: "2025-08-19 09:15 AM",
    staffName: "Vikram Rao",
    gender: "Female",
    dob: "02 May 1995",
    nationality: "Indian",
    govtIdType: "Aadhaar",
    govtIdNumber: "XXXX-XXXX-7812",
    email: "anjali.verma@gmail.com",
    aadhaarVerification: {
      status: "Verified",
      faceId: "Match",
      manualVerification: "Not Required",
      verifiedOn: "19 Aug 2025, 09:30 AM",
      verifiedBy: "HC-User215",
    },
    dependents: [],
  },
  {
    id: 5,
    reservation: "RES4005",
    name: "Mohammed Ali",
    hotel: "Silver Sands",
    location: "Banjara Hills, Hyderabad",
    phone: "9812345678",
    verification: "Aadhaar",
    faceMatch: "Match",
    checkIn: "2025-08-19 01:40 PM",
    staffName: "Kiran Patil",
    gender: "Male",
    dob: "07 Nov 1988",
    nationality: "Indian",
    govtIdType: "Aadhaar",
    govtIdNumber: "XXXX-XXXX-9910",
    email: "mohammed.ali@gmail.com",
    aadhaarVerification: {
      status: "Verified",
      faceId: "Match",
      manualVerification: "Not Required",
      verifiedOn: "19 Aug 2025, 01:55 PM",
      verifiedBy: "HC-User220",
    },
    dependents: [{ name: "Sara Ali", age: 6, guardian: "Mohammed Ali" }],
  },
  {
    id: 6,
    reservation: "RES4006",
    name: "Priyanka Desai",
    hotel: "Silver Sands",
    location: "Banjara Hills, Hyderabad",
    phone: "9765432109",
    verification: "Aadhaar",
    faceMatch: "Match",
    checkIn: "2025-08-20 10:00 AM",
    staffName: "Arvind Shetty",
    gender: "Female",
    dob: "29 Aug 1993",
    nationality: "Indian",
    govtIdType: "Aadhaar",
    govtIdNumber: "XXXX-XXXX-6712",
    email: "priyanka.desai@yahoo.com",
    aadhaarVerification: {
      status: "Verified",
      faceId: "Match",
      manualVerification: "Not Required",
      verifiedOn: "20 Aug 2025, 10:15 AM",
      verifiedBy: "HC-User230",
    },
    dependents: [],
  },
  {
    id: 7,
    reservation: "RES4007",
    name: "Rohit Gupta",
    hotel: "Silver Sands",
    location: "Banjara Hills, Hyderabad",
    phone: "9856741230",
    verification: "Driving License",
    faceMatch: "Match",
    checkIn: "2025-08-20 01:30 PM",
    staffName: "Deepika Menon",
    gender: "Male",
    dob: "11 Feb 1991",
    nationality: "Indian",
    govtIdType: "DL",
    govtIdNumber: "DL-AP-91823",
    email: "rohit.gupta@gmail.com",
    aadhaarVerification: {
      status: "Not Applicable",
      faceId: "Match",
      manualVerification: "Required",
      verifiedOn: "20 Aug 2025, 01:45 PM",
      verifiedBy: "HC-User240",
    },
    dependents: [],
  },
  {
    id: 8,
    reservation: "RES4008",
    name: "Samantha Lee",
    hotel: "Silver Sands",
    location: "Banjara Hills, Hyderabad",
    phone: "9761209345",
    verification: "Passport",
    faceMatch: "Match",
    checkIn: "2025-08-20 03:10 PM",
    staffName: "Anil Kumar",
    gender: "Female",
    dob: "18 Oct 1987",
    nationality: "American",
    govtIdType: "Passport",
    govtIdNumber: "P9012345",
    email: "samantha.lee@gmail.com",
    aadhaarVerification: {
      status: "Not Applicable",
      faceId: "Match",
      manualVerification: "Not Required",
      verifiedOn: "20 Aug 2025, 03:25 PM",
      verifiedBy: "HC-User245",
    },
    dependents: [],
  },
  {
    id: 9,
    reservation: "RES4009",
    name: "Krishna Reddy",
    hotel: "Silver Sands",
    location: "Banjara Hills, Hyderabad",
    phone: "9789012345",
    verification: "Aadhaar",
    faceMatch: "Match",
    checkIn: "2025-08-21 11:50 AM",
    staffName: "Shweta Singh",
    gender: "Male",
    dob: "06 Apr 1989",
    nationality: "Indian",
    govtIdType: "Aadhaar",
    govtIdNumber: "XXXX-XXXX-1111",
    email: "krishna.reddy@gmail.com",
    aadhaarVerification: {
      status: "Verified",
      faceId: "Match",
      manualVerification: "Not Required",
      verifiedOn: "21 Aug 2025, 12:05 PM",
      verifiedBy: "HC-User255",
    },
    dependents: [],
  },
  {
    id: 10,
    reservation: "RES4010",
    name: "Neha Kapoor",
    hotel: "Silver Sands",
    location: "Banjara Hills, Hyderabad",
    phone: "9821345690",
    verification: "Aadhaar",
    faceMatch: "Match",
    checkIn: "2025-08-21 02:15 PM",
    staffName: "Ravi Shankar",
    gender: "Female",
    dob: "14 Sep 1994",
    nationality: "Indian",
    govtIdType: "Aadhaar",
    govtIdNumber: "XXXX-XXXX-2211",
    email: "neha.kapoor@gmail.com",
    aadhaarVerification: {
      status: "Verified",
      faceId: "Match",
      manualVerification: "Not Required",
      verifiedOn: "21 Aug 2025, 02:30 PM",
      verifiedBy: "HC-User260",
    },
    dependents: [{ name: "Kabir Kapoor", age: 2, guardian: "Neha Kapoor" }],
  },
  {
    id: 11,
    reservation: "RES4011",
    name: "Rajesh Kumar",
    hotel: "Silver Sands",
    location: "Banjara Hills, Hyderabad",
    phone: "9845632190",
    verification: "Aadhaar",
    faceMatch: "Match",
    checkIn: "2025-08-22 10:20 AM",
    staffName: "Lakshmi Menon",
    gender: "Male",
    dob: "21 Dec 1982",
    nationality: "Indian",
    govtIdType: "Aadhaar",
    govtIdNumber: "XXXX-XXXX-7722",
    email: "rajesh.kumar@yahoo.com",
    aadhaarVerification: {
      status: "Verified",
      faceId: "Match",
      manualVerification: "Not Required",
      verifiedOn: "22 Aug 2025, 10:35 AM",
      verifiedBy: "HC-User265",
    },
    dependents: [],
  },
  {
    id: 12,
    reservation: "RES4012",
    name: "Ananya Iyer",
    hotel: "Silver Sands",
    location: "Banjara Hills, Hyderabad",
    phone: "9767890123",
    verification: "Aadhaar",
    faceMatch: "Match",
    checkIn: "2025-08-22 01:05 PM",
    staffName: "Harsh Vardhan",
    gender: "Female",
    dob: "19 Jun 1996",
    nationality: "Indian",
    govtIdType: "Aadhaar",
    govtIdNumber: "XXXX-XXXX-6622",
    email: "ananya.iyer@gmail.com",
    aadhaarVerification: {
      status: "Verified",
      faceId: "Match",
      manualVerification: "Not Required",
      verifiedOn: "22 Aug 2025, 01:20 PM",
      verifiedBy: "HC-User270",
    },
    dependents: [],
  },
  {
    id: 13,
    reservation: "RES4013",
    name: "James Smith",
    hotel: "Silver Sands",
    location: "Banjara Hills, Hyderabad",
    phone: "9701234567",
    verification: "Passport",
    faceMatch: "Match",
    checkIn: "2025-08-22 03:40 PM",
    staffName: "Pooja Rani",
    gender: "Male",
    dob: "03 May 1979",
    nationality: "Canadian",
    govtIdType: "Passport",
    govtIdNumber: "C8790123",
    email: "james.smith@gmail.com",
    aadhaarVerification: {
      status: "Not Applicable",
      faceId: "Match",
      manualVerification: "Not Required",
      verifiedOn: "22 Aug 2025, 03:55 PM",
      verifiedBy: "HC-User275",
    },
    dependents: [],
  },
  {
    id: 14,
    reservation: "RES4014",
    name: "Sneha Patil",
    hotel: "Silver Sands",
    location: "Banjara Hills, Hyderabad",
    phone: "9812233445",
    verification: "Aadhaar",
    faceMatch: "Match",
    checkIn: "2025-08-23 11:25 AM",
    staffName: "Suresh Babu",
    gender: "Female",
    dob: "27 Aug 1991",
    nationality: "Indian",
    govtIdType: "Aadhaar",
    govtIdNumber: "XXXX-XXXX-9923",
    email: "sneha.patil@gmail.com",
    aadhaarVerification: {
      status: "Verified",
      faceId: "Match",
      manualVerification: "Not Required",
      verifiedOn: "23 Aug 2025, 11:40 AM",
      verifiedBy: "HC-User280",
    },
    dependents: [],
  },
  {
    id: 15,
    reservation: "RES4015",
    name: "Amit Chawla",
    hotel: "Silver Sands",
    location: "Banjara Hills, Hyderabad",
    phone: "9798765432",
    verification: "Aadhaar",
    faceMatch: "Match",
    checkIn: "2025-08-23 01:50 PM",
    staffName: "Geeta Rani",
    gender: "Male",
    dob: "30 Nov 1987",
    nationality: "Indian",
    govtIdType: "Aadhaar",
    govtIdNumber: "XXXX-XXXX-7729",
    email: "amit.chawla@gmail.com",
    aadhaarVerification: {
      status: "Verified",
      faceId: "Match",
      manualVerification: "Not Required",
      verifiedOn: "23 Aug 2025, 02:05 PM",
      verifiedBy: "HC-User285",
    },
    dependents: [{ name: "Rohan Chawla", age: 4, guardian: "Amit Chawla" }],
  },
];